# Generated by Django 4.2.29 on 2026-07-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZMockApiDbConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='连接标识')),
                ('db_type', models.CharField(default='mysql', max_length=32, verbose_name='数据库类型')),
                ('host', models.CharField(max_length=128, verbose_name='主机地址')),
                ('port', models.PositiveIntegerField(default=3306, verbose_name='端口')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=256, verbose_name='密码')),
                ('database', models.CharField(max_length=128, verbose_name='数据库名')),
                ('status', models.SmallIntegerField(default=1, help_text='1-启用 0-停用', verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=512, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Mock API 数据库配置',
                'verbose_name_plural': 'Mock API 数据库配置',
                'db_table': 'z_mock_api_db_config',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ZMockApiRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('url_pattern', models.CharField(help_text='拦截的 URL 或关键字', max_length=512, verbose_name='URL 匹配模式')),
                ('match_type', models.CharField(choices=[('contains', '包含'), ('regex', '正则'), ('exact', '精确')], default='contains', max_length=32, verbose_name='匹配方式')),
                ('response_file', models.CharField(blank=True, default='', help_text='JSON 响应数据文件路径（最高优先级）', max_length=512, verbose_name='响应数据文件')),
                ('response_data', models.TextField(blank=True, default='', help_text='直接填入的 JSON 响应数据（可作为数据库查询降级 fallback）', verbose_name='内联响应数据')),
                ('response_sql', models.TextField(blank=True, default='', help_text='命中规则时实时执行的 SQL 查询', verbose_name='SQL 查询语句')),
                ('response_db', models.TextField(blank=True, default='', help_text='JSON 格式的数据库连接信息: {host, port, username, password, database, db_type}', verbose_name='数据库连接配置')),
                ('status_code', models.PositiveIntegerField(default=200, verbose_name='响应 HTTP 状态码')),
                ('status', models.SmallIntegerField(default=1, help_text='1-启用 0-停用', verbose_name='状态')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('remark', models.CharField(blank=True, default='', max_length=512, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Mock API 规则',
                'verbose_name_plural': 'Mock API 规则',
                'db_table': 'z_mock_api_rule',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
