# Generated by Django 4.2.29 on 2026-08-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zmockapirule',
            name='response_data',
            field=models.TextField(blank=True, default='', help_text='直接填入的响应数据，支持 JSON 或非 JSON 格式（纯文本、base64 字符串等），可作为数据库查询降级 fallback', verbose_name='内联响应数据'),
        ),
    ]
