# Generated by Django 4.2.29 on 2026-04-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('task_code', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='任务编码')),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='说明')),
                ('cron_expression', models.CharField(max_length=128, verbose_name='Cron 表达式')),
                ('status', models.SmallIntegerField(default=1, help_text='1-启用 0-停用', verbose_name='状态')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最近执行')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'db_table': 'z_scheduled_task',
                'ordering': ['-id'],
            },
        ),
    ]
